# Generated by Django 3.2.5 on 2021-08-10 18:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_auto_20210804_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='watching', max_length=20)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_change', models.DateField(default=datetime.date(2021, 8, 10))),
                ('access', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='movie')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.rate', verbose_name='rate')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.status', verbose_name='status')),
            ],
            options={
                'verbose_name': 'Movie List',
                'verbose_name_plural': 'Movie Lists',
            },
        ),
    ]
