# Generated by Django 3.2.5 on 2021-08-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(default='movies/default_poster.png', upload_to='directors/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='movies/default_poster.png', upload_to='movies/', verbose_name='Poster'),
        ),
    ]
